# Generated by Django 5.0.2 on 2024-02-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='secondname',
        ),
        migrations.AddField(
            model_name='persona',
            name='birthdate',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
        migrations.AlterModelTable(
            name='prestamo',
            table='prestamo',
        ),
        migrations.AlterModelTable(
            name='rawsolicitud',
            table='raw_solicitud',
        ),
        migrations.AlterModelTable(
            name='solicitud',
            table='solicitud',
        ),
    ]
